# Generated by Django 4.2.7 on 2023-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_pull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
